version: 2
jobs:
  build:
    working_directory: /go/src/github.com/silverstripeltd/s3sync
    parallelism: 1
    environment:
      TEST_RESULTS: /tmp/circleci-test-results
    # https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
           # This branch if available
          - v1-pkg-cache-{{ .Branch }}
           # Default branch if not
          - v1-pkg-cache-master
           # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v1-dep-cache
      - run: go get -t -d -v ./...
      - run: go get -v github.com/kisielk/errcheck
      - run: go get -v github.com/golang/lint/golint
      - run: go get -v github.com/opennota/check/cmd/varcheck
      - run: go get github.com/jstemmer/go-junit-report
      - run: go build -v
      # Save dependency cache
      - save_cache:
          key: v1-pkg-cache-{{ .Branch }}
          paths:
            - "/go/pkg"
      # Test
      - run:
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      # Teardown
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
